# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_level_block_design/top_level_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design || ORIG_REF_NAME==top_level_block_design} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==top_level_block_design_zynq_ultra_ps_e_0_3} -quiet] -quiet

# XDC: bd/top_level_block_design/top_level_block_design_ooc.xdc
