# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_level_block_design/top_level_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design || ORIG_REF_NAME==top_level_block_design} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==top_level_block_design_zynq_ultra_ps_e_0_3} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_usp_rf_data_converter_0_0/top_level_block_design_usp_rf_data_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_block_design_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_ps8_0_axi_periph_0/top_level_block_design_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_ps8_0_axi_periph_0 || ORIG_REF_NAME==top_level_block_design_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_rst_ps8_0_99M_0/top_level_block_design_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_rst_ps8_0_99M_0 || ORIG_REF_NAME==top_level_block_design_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_system_ila_0_0/top_level_block_design_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_system_ila_0_0 || ORIG_REF_NAME==top_level_block_design_system_ila_0_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_gpio_to_fifo_0_0/top_level_block_design_gpio_to_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_gpio_to_fifo_0_0 || ORIG_REF_NAME==top_level_block_design_gpio_to_fifo_0_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_fifo_generator_0_0/top_level_block_design_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_fifo_generator_0_0 || ORIG_REF_NAME==top_level_block_design_fifo_generator_0_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_pulse_gen_0_0/top_level_block_design_pulse_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_pulse_gen_0_0 || ORIG_REF_NAME==top_level_block_design_pulse_gen_0_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_proc_sys_reset_0_0/top_level_block_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_proc_sys_reset_0_0 || ORIG_REF_NAME==top_level_block_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/top_level_block_design_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_system_ila_1_0 || ORIG_REF_NAME==top_level_block_design_system_ila_1_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_auto_ds_0/top_level_block_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_auto_ds_0 || ORIG_REF_NAME==top_level_block_design_auto_ds_0} -quiet] -quiet

# IP: bd/top_level_block_design/ip/top_level_block_design_auto_pc_0/top_level_block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_block_design_auto_pc_0 || ORIG_REF_NAME==top_level_block_design_auto_pc_0} -quiet] -quiet

# XDC: bd/top_level_block_design/top_level_block_design_ooc.xdc
