# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/James/test_project/test_project.runs/synth_1/top_level_block_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu28dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/James/test_project/test_project.cache/wt [current_project]
set_property parent.project_path C:/James/test_project/test_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu111:part0:1.2 [current_project]
set_property ip_output_repo c:/James/test_project/test_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/James/verilog_source/shift_register.v
  C:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/hdl/top_level_block_design_wrapper.v
}
add_files C:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/top_level_block_design.bd
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_usp_rf_data_converter_0_0/synth/top_level_block_design_usp_rf_data_converter_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_usp_rf_data_converter_0_0/synth/top_level_block_design_usp_rf_data_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_usp_rf_data_converter_0_0/synth/top_level_block_design_usp_rf_data_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_rst_ps8_0_99M_0/top_level_block_design_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_rst_ps8_0_99M_0/top_level_block_design_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_rst_ps8_0_99M_0/top_level_block_design_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_fifo_generator_0_0/top_level_block_design_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_fifo_generator_0_0/top_level_block_design_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_fifo_generator_0_0/top_level_block_design_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_proc_sys_reset_0_0/top_level_block_design_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_proc_sys_reset_0_0/top_level_block_design_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_proc_sys_reset_0_0/top_level_block_design_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_clk_wiz_0_0/top_level_block_design_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_clk_wiz_0_0/top_level_block_design_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_clk_wiz_0_0/top_level_block_design_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_xbar_0/top_level_block_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_axi_gpio_0_0/top_level_block_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_axi_gpio_0_0/top_level_block_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_axi_gpio_0_0/top_level_block_design_axi_gpio_0_0.xdc]
set_property used_in_synthesis false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/bd_da80_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/bd_da80_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/top_level_block_design_system_ila_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_auto_ds_0/top_level_block_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_auto_ds_0/top_level_block_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_auto_ds_0/top_level_block_design_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_auto_pc_0/top_level_block_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/top_level_block_design_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_usp_rf_data_converter_0_0/data/startup.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_level_block_design_wrapper -part xczu28dr-ffvg1517-2-e
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level_block_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_block_design_wrapper_utilization_synth.rpt -pb top_level_block_design_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
