# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/top_level_block_design_system_ila_1_0.xci
# IP: The module: 'top_level_block_design_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/bd_da80.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_da80 || ORIG_REF_NAME==bd_da80} -quiet] -quiet

# IP: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/bd_da80_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_da80_ila_lib_0 || ORIG_REF_NAME==bd_da80_ila_lib_0} -quiet] -quiet

# IP: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_1/bd_da80_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_da80_g_inst_0 || ORIG_REF_NAME==bd_da80_g_inst_0} -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_da80_ila_lib_0 || ORIG_REF_NAME==bd_da80_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_da80_ila_lib_0 || ORIG_REF_NAME==bd_da80_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/bd_da80_ila_lib_0_ooc.xdc

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/bd_da80_ooc.xdc

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/top_level_block_design_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_design_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/top_level_block_design_system_ila_1_0.xci
# IP: The module: 'top_level_block_design_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/bd_da80.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_da80 || ORIG_REF_NAME==bd_da80} -quiet] -quiet

# IP: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/bd_da80_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_da80_ila_lib_0 || ORIG_REF_NAME==bd_da80_ila_lib_0} -quiet] -quiet

# IP: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_1/bd_da80_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_da80_g_inst_0 || ORIG_REF_NAME==bd_da80_g_inst_0} -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_da80_ila_lib_0 || ORIG_REF_NAME==bd_da80_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_da80_ila_lib_0 || ORIG_REF_NAME==bd_da80_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/ip/ip_0/bd_da80_ila_lib_0_ooc.xdc

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/bd_0/bd_da80_ooc.xdc

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_system_ila_1_0/top_level_block_design_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_design_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
