# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xci
# IP: The module: 'top_level_block_design_zynq_ultra_ps_e_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_design_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_design_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xci
# IP: The module: 'top_level_block_design_zynq_ultra_ps_e_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_design_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/James/test_project/test_project.srcs/sources_1/bd/top_level_block_design/ip/top_level_block_design_zynq_ultra_ps_e_0_3/top_level_block_design_zynq_ultra_ps_e_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_design_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
