copy /Y C:\zcu111_ipi_xm107\ready_for_download\hello_pmod.bit .\zcu111_hello_pmod.bit
copy /Y C:\zcu111_ipi_xm107\ready_for_download\xm500_dacio.bit .\zcu111_xm500_dacio.bit
copy /Y C:\zcu111_ipi_xm107\ready_for_download\xm107_lvds.bit .\zcu111_xm107_lvds.bit
copy /Y C:\zcu111_mig\ready_for_download\debug_nets.ltx .\zcu111_mig_pl_ddr4.ltx
copy /Y C:\zcu111_mig\ready_for_download\example_top.bit .\zcu111_mig_pl_ddr4.bit
copy /Y C:\zcu111_ibert\ready_for_download\ibert_bank_all.bit .\zcu111_ibert_bank_all.bit
copy /Y C:\zcu111_ipi\ready_for_download\zcu111_ipi.bit .\zcu111_ipi.bit
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\hello_uart_2\Debug\hello_uart_2.elf ..\elf
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\ipi_app\Debug\ipi_app.elf ..\elf
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\lwip_echo_server\Debug\lwip_echo_server.elf ..\elf
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\zynq_mp_fsbl\Debug\zynq_mp_fsbl.elf ..\elf\qspi_zynq_mp_fsbl.elf
copy /Y C:\zcu111_restore_flash\blinkbist.mcs .\blinkbist.mcs
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\zynq_mp_dram_test\Debug\zynq_mp_dram_test.elf ..\elf
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\system_wrapper_hw_platform_0\psu_init.tcl ..\tcl\ipi_psu_init.tcl
copy /Y C:\zcu111_ipi\zcu111_ipi.sdk\hello_rtc\Debug\hello_rtc.elf ..\elf
copy /Y C:\zcu111_bsl\ready_for_download\boot_strap_loader.bit .
copy /Y C:\zcu111_bsl\ready_for_download\boot_strap_loader.elf ..\elf
copy /Y C:\zcu111_bsl\ready_for_download\MSP_code.txt ..\elf
copy /Y C:\zcu111_bsl\ready_for_download\MSP_code.txt ..\bat\msp_flash
copy /Y C:\zcu111_bsl\ready_for_download\psu_init.tcl ..\tcl\bsl_psu_init.tcl
copy /Y C:\zcu111_level_shifters\ready_for_download\level_shifters.bit .\level_shifters.bit
copy /Y C:\zcu111_level_shifters\ready_for_download\level_shifters.elf ..\elf
copy /Y C:\zcu111_level_shifters\ready_for_download\level_shifters_psu_init.tcl ..\tcl
pause
